'use client'

import { CloseCircle } from 'iconsax-react'
import { Lightbulb } from 'lucide-react'

import { Button } from '@/components/ui/button'
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerTrigger
} from '@/components/ui/drawer'

import StepAccordion from './tutorial-step-accordian'

// tutorialData.ts
const tutorialData = {
  offline: {
    title: 'How to bring your offline partners online?',
    description: 'Please follow the steps below to bring your partner online.',
    steps: [
      {
        id: 1,
        title: 'Send link to join you on Sharkdom',
        description:
          '<p>Integrate your existing partners into the Sharkdom platform by sending them a unique join link. This allows for centralized management of all partnerships, including onboarding, communication, and collaboration, within the platform.</p>'
      },
      {
        id: 2,
        title: 'Manage contracts online',
        description:
          '<p>Upload your existing partner contracts to the platform for centralized management.</p>'
      },
      {
        id: 3,
        title: 'Use Email Campaign',
        description: `
            <ol>
              <li>1. Automate emails: Use the Email Campaign Trigger to create and schedule personalized email sequences for your partners.</li>
              <li>2. Reduce manual effort: Eliminate the need for manual email composition, sending, and tracking through automation.</li>
              <li>3. Ensure consistent communication: Maintain regular contact with all partners through automated email campaigns, replacing outdated spreadsheets and manual reminders.</li>
            </ol>
          `
      }
    ]
  },

  partners: {
    title: 'How to establish partnerships better?',
    description: 'Please follow below steps to build better partnerships.',
    steps: [
      {
        id: 1,
        title: 'Send a partnership proposal',
        description: `
            <p>Send your proposal by clicking on <strong>Send Proposal</strong> and modify the terms and conditions if necessary.</p>
            <p>You can also generate the proposal using our AI tool.</p>
          `
      },
      {
        id: 2,
        title: 'Wait for Acknowledgment',
        description: `
            <ol>
              <li>Allow sufficient review time.</li>
              <li>Encourage questions from the other party.</li>
              <li>Be Communicative: Set up communication channels like Email, WhatsApp groups, and more.</li>
              <li>Confirm understanding of the proposal.</li>
            </ol>
          `
      },
      {
        id: 3,
        title: 'Cooldown Period',
        description: `
            <ol>
              <li>1.Implement a 12-hour cooldown period after the proposal is acknowledged, allowing both parties to evaluate the partnership independently.</li>
              <li>2.Only the recipient of the proposal can initiate a meeting during this time.</li>
            </ol>
          `
      },
      {
        id: 4,
        title: 'Setup a meeting (Optional)',
        description: `
            <p>Upon acceptance of the proposal, suggest a follow-up meeting to discuss details further, fostering trust and improving the likelihood of a successful partnership.</p>
          `
      },
      {
        id: 5,
        title: 'MoU Generation',
        description:
          '<p>Upon mutual agreement to the proposal, both parties will receive a digitally signed Memorandum of Understanding (MoU) generated by Sharkdom. The receiving party will be the first to receive the executed MoU, followed by the sending party.</p>'
      },
      {
        id: 6,
        title: 'Access to Partner Valve Room',
        description: `
            <p>Following the execution of the MoU, both parties will be granted access to a shared, secure online workspace (<strong>Partner Vault</strong>) to facilitate direct communication and collaboration.</p>
          `
      },
      {
        id: 7,
        title: 'Follow-Ups',
        description: `
            <p>Once the partnership is established, maintain regular follow-ups with the other party to ensure progress and address any issues or concerns that arise promptly. Promote open communication and foster a positive working relationship.</p>
          `
      }
    ]
  },
  persona: {
    title: 'How to create customer persona?',
    description:
      'Please follow below steps to create customer persona with ease.',
    steps: [
      {
        id: 1,
        title: 'Get ready with your customer Data file',
        description: `
            <ol>
              <li>Gather customer data: Use a CSV file, HubSpot, or Google Sheet.</li>
              <li>Include website addresses:  Ensure your data contains a column with customer website addresses.</li>
              <li>Prepare for next steps: This data will be used for further analysis.</li>
            </ol>
          `
      },
      {
        id: 2,
        title: 'Upload Your Data',
        description: `<ol>
          <li>Choose your method: Upload via CSV, Connect with HubSpot, or Google Sheet.</li>
          <li>Secure Upload: Upload your customer data to Sharkdom.</li>
          <li>Privacy Assured:  Sharkdom does not store your data; privacy is a priority.</li>
        </ol>`
      },
      {
        id: 3,
        title: 'Persona Generation',
        description:
          '<p>Click on create persona and wait for magic, Allow us 15 minutes for to process your data and generate your customer personas.</p>'
      },
      {
        id: 4,
        title: 'Access Your Personas',
        description: `<p>Ola! u can access your vein diagram from marketplace and also from my profile.</p>`
      }
    ]
  },
  onboarding: {
    title: 'Getting Started with Our Platform',
    description:
      'Learn how to set up your account and onboard your team efficiently.',
    steps: [
      {
        id: 1,
        title: 'Setup Your Account',
        description:
          '<p>Complete your profile and configure basic settings to get started with our platform.</p>'
      },
      {
        id: 2,
        title: 'Invite Your Team',
        description:
          '<p>Add team members to your account and assign roles to ensure seamless collaboration.</p>'
      },
      {
        id: 3,
        title: 'Learn the Dashboard',
        description:
          '<p>Take a quick tour of the dashboard to familiarize yourself with key features and tools.</p>'
      }
    ]
  }
}
export function TutorialDrawer({ type }: { type: string }) {
  const tutorial = tutorialData[type as keyof typeof tutorialData]

  if (!tutorial) {
    return <p className='text-center text-gray-500'>Tutorial not found.</p>
  }

  const { title, description, steps } = tutorial
  return (
    <Drawer>
      <DrawerTrigger asChild className=''>
        <Button className='learn flex items-center gap-1 rounded-lg px-8 text-shark-xl text-white hover:bg-primary-dark-blue hover:text-white'>
          <Lightbulb size={16} />
          Learn
        </Button>
      </DrawerTrigger>

      <DrawerContent className=' hide-scrollbar right-0 max-w-[498px] overflow-y-auto overflow-x-hidden px-5   py-4 lg:w-[498px]'>
        <DrawerHeader>
          <div className='flex items-center justify-between'>
            <div className='flex items-center gap-2'>
              <h3 className='fds-heading text-text-100'>Tutorials</h3>
            </div>

            <DrawerClose asChild>
              <Button variant='link'>
                <CloseCircle size={32} color='#2A3241' />
              </Button>
            </DrawerClose>
          </div>
        </DrawerHeader>
        <div className='mt-10 flex flex-col px-5'>
          <h3 className='mb-2 text-shark-lg font-bold text-text-100'>
            {title}
          </h3>
          <p className='mb-10 text-shark-sm text-text-60'>{description}</p>

          <StepAccordion steps={steps} />
        </div>
      </DrawerContent>
    </Drawer>
  )
}
